name: test-adopt-info
base: core22
adopt-info: mypartname
summary: Set snap version programatically
description: |
  Boilerplate
grade: devel
confinement: strict

parts:
  mypartname:
    plugin: nil
    override-pull: |
      GIT_REVISION=$(git describe --always --dirty)
      craftctl set version=${GIT_REVISION}
    build-packages: [ git ]
