name: env0
base: core22
version: '0.1'
summary: demo for how to set environment variables
description: |
  Show how to set environment variables in snapcraft.yaml.

grade: stable
confinement: strict

environment:
  FLAVOUR: "vanilla for everyone"

apps:
  a1:
    command: app1.sh
  a2:
    command: app2.sh
    environment:
      FLAVOUR: "crunchy frog"

parts:
  a1:
    source: app1
    plugin: dump
  a2:
    source: app2
    plugin: dump
