name: gotop
base: core24
version: '4.2.0'
summary: A terminal based graphical activity monitor inspired by gtop and vtop
description: |
  This is an unofficial build of gotop as a snap package.

  This is meant solely as an example for how a "simple" snap could be
  constructed, and the process by which that should be accomplished.

  The work in this repository belongs to Canonical and is licensed CC-BY-SA-4.0
  The contents of this snap which aren't works from this repository are licensed
  MIT.

website: https://github.com/xxxserxxx/gotop
# We might want to link to issues in the future,
# but we shouldn't direct people to upstream
#issues: <future URL>

# The source code for this snap package may be hosted on e.g. GitHub:
#source-code: <future URL>

# The license specified includes the license of all artifacts distributed by the snap
license: "CC-BY-SA-4.0 AND MIT"

# Leave grade and confinement as devel and devmode until we're ready for a release.
grade: devel
confinement: devmode
